### ISSUE TITLE
Plugin doesn't work with prettier-plugin-organize-imports

### ISSUE THREAD

**Issue by dave4506** [wasm-ecosystem/assemblyscript-prettier#13]
I use `[prettier-plugin-organize-imports](https://github.com/simonhaenisch/prettier-plugin-organize-imports)` in my prettier plugins and it appears to stop working when I also use `assemblyscript-prettier`, not quite sure why.

If there is a fix or some idea why this is the case that would be great!

**Comment by HerrCai0907** [comment]
please check the prettier version. most of crash is due to prettier major version upgrade from 2 to 3, aka from cjs to esm.

**Comment by HerrCai0907** [comment]
close the stable issue.
